spring:
  application:
    name: demo

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: demo

  prometheus:
    metrics:
      export:
        enabled: true